'use client'

import '@/app/globals.css'
import '@/app/css/nucleo-icons.css'
import {Open_Sans} from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'

const open_sans = Open_Sans({subsets: ['latin'], weight: ["300", "400", "500", "600", "700", "800"]})

export const metadata = {
  title: 'Cash Flows',
  description: 'Generated by create next app',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const classes = `${open_sans.className}`

  return (
    <html lang="pt">
      <body>
        <StyledComponentsRegistry>
          <div
            className={classes}
          >
            {children}
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
